### ISSUE TITLE
Checklist for 3.0.0

### ISSUE THREAD

**Issue by smoelius** [trailofbits/dylint#974]
- [x] Remove deprecated command line options:
  - https://github.com/trailofbits/dylint/blob/d83a006ea7cdd41ed02576c777953d097956297f/cargo-dylint/src/main.rs#L283-L306
  - https://github.com/trailofbits/dylint/blob/d83a006ea7cdd41ed02576c777953d097956297f/dylint/src/lib.rs#L118-L124
- [x] Remove `metadata` as a default feature in the `dylint` library: https://github.com/trailofbits/dylint/blob/d83a006ea7cdd41ed02576c777953d097956297f/dylint/Cargo.toml#L63-L65
- [x] Make `deny_warnings` not a default feature in `dylint_testing`: https://github.com/trailofbits/dylint/blob/d83a006ea7cdd41ed02576c777953d097956297f/utils/testing/Cargo.toml#L24
- [x] Remove experimental `--bisect` option: https://github.com/trailofbits/dylint/blob/7f05df13058f05b3b8c7330edcc9d25e0320dd36/dylint/src/lib.rs#L140
- [x] Rename features `metadata-cargo` and `metadata-cli` to `cargo-lib` and `cargo-cli` (respectively), and make the latter the default: https://github.com/trailofbits/dylint/blob/7ab04c8a14aa02030bc6639bb08f2a1c4677b6f0/cargo-dylint/Cargo.toml#L42-L44
- [x] Make the `cargo-cli` download method the default

**Comment by smoelius** [comment]
Leaving this open until 3.0.0 is released.

**Comment by smoelius** [comment]
3.0.0 is released.
